title: "Creating graphs in R with `ggplot2`"
author: "Katie"
date: "8/3/22"
output: html_document
---

# Plots with ggplot2

Test plots wit R for R4Excel Course.---

library(tidyverse)
library(readxl)
library(here)

ca_np <- read_csv(here("data", "ca_np.csv"))

names(ca_np)
head(ca_np)
summary(ca_np)

ci_np <- read_excel(here("data", "ci_np.xlsx"))

Code for ggplot graphs: "ggplot(data = df_name, aes(x = x_var_name, y = y_var_name)) +  geom_type()"

ggplot(data = ci_np, aes(x = year, y = visitors)) + geom_line()

ggplot(data = ci_np, aes(x = year, y = visitors)) + geom_point()

ggplot(data = ci_np, aes(x = year, y = visitors)) + geom_col()

gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))

gg_base + geom_smooth()

gg_base + geom_area()

gg_base +
  geom_line(
    color = "purple",
    linetype = "dashed"
  )



gg_base + 
  geom_smooth(color = "green4",
             pch = 8,
             size = 2,
             alpha = 1)
   gg_base + 
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  )          

   gg_base + 
  geom_col(aes(fill = visitors))          

gg_base +
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  ) +
  theme_minimal()
  
  gg_base +
  geom_line(
    color = "green4",
    linetype = "dashed"
  ) +
  theme_light()

  gg_base +
  geom_line(linetype = "dotted") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
  )
# Label formatters
library(scales)   # Need the scales package
example scale code:  #bp + scale_y_continuous(labels=percent) +
     scale_x_discrete(labels=abbreviate)  # 

  gg_base +
  geom_line(linetype = "dotted") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
  ) + scale_y_continuous(labels=comma)

  gg_base +
  geom_col(fill = "orange",
           color = "purple") +
  geom_line(color = "green")


  ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name)) +
  geom_line()
  
  gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))

 ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name, colour = park_name) +
  geom_line() 
  
gg_np +
  geom_line(show.legend = FALSE) +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)

  gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))

 gg_np +
  geom_line(show.legend = FALSE) +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name) + scale_y_continuous(labels=comma)

ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)
  
  